name: my_binder_environment
channels:
  - defaults
dependencies:
  - python=3.8.10
  - numpy
  - ipywidgets
  - ipycanvas
  - tensorflow
  - scikit-learn
  - opencv-python-headless
  - voila
  - pip:
      - ipycanvas
